version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"

  auth-api:
    extends:
      file: ./compose/compose.local.yml
      service: auth-api
    depends_on:
      - mariadb

  user-api:
    extends:
      file: ./compose/compose.local.yml
      service: user-api
    depends_on:
      - mariadb

  task-api:
    extends:
      file: ./compose/compose.local.yml
      service: task-api
    depends_on:
      - mongo

  media-api:
    extends:
      file: ./compose/compose.local.yml
      service: media-api
    depends_on:
      - mariadb

  front:
    extends:
      file: ./compose/compose.local.yml
      service: front

networks:
  default:
    external: true
    name: grpc-task-manager_default
