version: '3.8'

services:
  mariadb:
    extends:
      file: ./compose/compose.db.yml
      service: mariadb

  mongo:
    extends:
      file: ./compose/compose.db.yml
      service: mongo

  mongo-car:
    extends:
      file: ./compose/compose.db.yml
      service: mongo-car

  mongo-race:
    extends:
      file: ./compose/compose.db.yml
      service: mongo-race

  tracing:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 14268:14268
      - 4318:4318

  auth-api:
    extends:
      file: ./compose/compose.local.yml
      service: auth-api

  user-api:
    extends:
      file: ./compose/compose.local.yml
      service: user-api

  task-api:
    extends:
      file: ./compose/compose.local.yml
      service: task-api
  
  car-api:
    extends:
      file: ./compose/compose.local.yml
      service: car-api

  race-api:
    extends:
      file: ./compose/compose.local.yml
      service: race-api

networks:
  default:
    external: true
    name: grpc-task-manager_default
