// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "race/message.proto" (package "race", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message race.Race
 */
export interface Race {
    /**
     * @generated from protobuf field: int32 race_id = 1;
     */
    raceId: number;
    /**
     * @generated from protobuf field: int32 driver_id = 2;
     */
    driverId: number;
    /**
     * @generated from protobuf field: int32 car_id = 3;
     */
    carId: number;
    /**
     * @generated from protobuf field: string name = 4;
     */
    name: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Race$Type extends MessageType<Race> {
    constructor() {
        super("race.Race", [
            { no: 1, name: "race_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "driver_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "car_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Race>): Race {
        const message = { raceId: 0, driverId: 0, carId: 0, name: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Race>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Race): Race {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 race_id */ 1:
                    message.raceId = reader.int32();
                    break;
                case /* int32 driver_id */ 2:
                    message.driverId = reader.int32();
                    break;
                case /* int32 car_id */ 3:
                    message.carId = reader.int32();
                    break;
                case /* string name */ 4:
                    message.name = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Race, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 race_id = 1; */
        if (message.raceId !== 0)
            writer.tag(1, WireType.Varint).int32(message.raceId);
        /* int32 driver_id = 2; */
        if (message.driverId !== 0)
            writer.tag(2, WireType.Varint).int32(message.driverId);
        /* int32 car_id = 3; */
        if (message.carId !== 0)
            writer.tag(3, WireType.Varint).int32(message.carId);
        /* string name = 4; */
        if (message.name !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.name);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message race.Race
 */
export const Race = new Race$Type();
