// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "race/service.proto" (package "race", syntax proto3)
// tslint:disable
import { UnSubscribeRaceParticipationResponse } from "./request";
import { UnSubscribeRaceParticipationRequest } from "./request";
import { SubscribeRaceParticipationResponse } from "./request";
import { SubscribeRaceParticipationRequest } from "./request";
import { DeleteRaceResponse } from "./request";
import { DeleteRaceRequest } from "./request";
import { UpdateRaceResponse } from "./request";
import { UpdateRaceRequest } from "./request";
import { CreateRaceResponse } from "./request";
import { CreateRaceRequest } from "./request";
import { GetRaceResponse } from "./request";
import { GetRaceRequest } from "./request";
import { ListRacesResponse } from "./request";
import { ListRacesRequest } from "./request";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service race.RaceService
 */
export const RaceService = new ServiceType("race.RaceService", [
    { name: "ListRaces", options: {}, I: ListRacesRequest, O: ListRacesResponse },
    { name: "GetRace", options: {}, I: GetRaceRequest, O: GetRaceResponse },
    { name: "CreateRace", options: {}, I: CreateRaceRequest, O: CreateRaceResponse },
    { name: "UpdateRace", options: {}, I: UpdateRaceRequest, O: UpdateRaceResponse },
    { name: "DeleteRace", options: {}, I: DeleteRaceRequest, O: DeleteRaceResponse },
    { name: "SubscribeRaceParticipation", options: {}, I: SubscribeRaceParticipationRequest, O: SubscribeRaceParticipationResponse },
    { name: "UnSubscribeRaceParticipation", options: {}, I: UnSubscribeRaceParticipationRequest, O: UnSubscribeRaceParticipationResponse }
]);
