apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: user-api-selfsigned-cert
spec:
  dnsNames:
    - user-api.grpc-tm
    - localhost
  secretName: user-api-cert-tls
  issuerRef:
    name: tm-selfsigned

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-api-selfsigned-cert
spec:
  dnsNames:
    - auth-api.grpc-tm
    - localhost
  secretName: auth-api-cert-tls
  issuerRef:
    name: tm-selfsigned

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: task-api-selfsigned-cert
spec:
  dnsNames:
    - task-api.grpc-tm
    - localhost
  secretName: task-api-cert-tls
  issuerRef:
    name: tm-selfsigned
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: front-selfsigned-cert
spec:
  dnsNames:
    - front.grpc-tm
    - localhost
  secretName: front-cert-tls
  issuerRef:
    name: tm-selfsigned
