// @generated by protobuf-ts 2.9.0
// @generated from protobuf file "timesheet/v1_alpha/timesheet.proto" (package "timesheet.v1alpha", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TimesheetCRUDService } from "./timesheet";
import type { DeleteResponse } from "./timesheet";
import type { DeleteRequest } from "./timesheet";
import type { UpdateResponse } from "./timesheet";
import type { UpdateRequest } from "./timesheet";
import type { AddResponse } from "./timesheet";
import type { AddRequest } from "./timesheet";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetResponse } from "./timesheet";
import type { GetRequest } from "./timesheet";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service timesheet.v1alpha.TimesheetCRUDService
 */
export interface ITimesheetCRUDServiceClient {
    /**
     * @generated from protobuf rpc: Get(timesheet.v1alpha.GetRequest) returns (timesheet.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse>;
    /**
     * @generated from protobuf rpc: Add(timesheet.v1alpha.AddRequest) returns (timesheet.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse>;
    /**
     * @generated from protobuf rpc: Update(timesheet.v1alpha.UpdateRequest) returns (timesheet.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse>;
    /**
     * @generated from protobuf rpc: Delete(timesheet.v1alpha.DeleteRequest) returns (timesheet.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse>;
}
/**
 * @generated from protobuf service timesheet.v1alpha.TimesheetCRUDService
 */
export class TimesheetCRUDServiceClient implements ITimesheetCRUDServiceClient, ServiceInfo {
    typeName = TimesheetCRUDService.typeName;
    methods = TimesheetCRUDService.methods;
    options = TimesheetCRUDService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Get(timesheet.v1alpha.GetRequest) returns (timesheet.v1alpha.GetResponse);
     */
    get(input: GetRequest, options?: RpcOptions): UnaryCall<GetRequest, GetResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRequest, GetResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Add(timesheet.v1alpha.AddRequest) returns (timesheet.v1alpha.AddResponse);
     */
    add(input: AddRequest, options?: RpcOptions): UnaryCall<AddRequest, AddResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddRequest, AddResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Update(timesheet.v1alpha.UpdateRequest) returns (timesheet.v1alpha.UpdateResponse);
     */
    update(input: UpdateRequest, options?: RpcOptions): UnaryCall<UpdateRequest, UpdateResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateRequest, UpdateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Delete(timesheet.v1alpha.DeleteRequest) returns (timesheet.v1alpha.DeleteResponse);
     */
    delete(input: DeleteRequest, options?: RpcOptions): UnaryCall<DeleteRequest, DeleteResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteRequest, DeleteResponse>("unary", this._transport, method, opt, input);
    }
}
