apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grpc-tm


configMapGenerator:
- envs:
  - config.properties
  name: api-map
generatorOptions:
  disableNameSuffixHash: true
resources:
- ../../deployment
- ../../certs
- ../../observability
- ../../front
