- op: replace
  path: /spec/template/spec/containers/volumes/-
  value:
    name: tls
    csi:
      driver: csi.cert-manager.io
      readOnly: true
      volumeAttributes:
        csi.cert-manager.io/issuer-name: tm-selfsigned
        csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}

# - op: add
#   path: /spec/template/spec/containers/0/volumeMounts/-
#   value:
#     name: tls
#     mountPath: "/certs"
#     readOnly: true