version: '3.8'

services:
  user-api:
    image: mohammaddocker/tm-user-api
    environment:
      - MYSQL_URL=mysql://root:passwd@mariadb:3306/user
      - insecure=false
      - USER_CERT=/certs/user.pem
      - USER_KEY=/certs/user-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - PORT=4000
      - AUTH_API_URL=auth-api:4000
      - JAEGER_URL=http://tracing:4318/v1/traces
    # ports:
    #   - 4000:4000
    volumes:
      - ../local/certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

  task-api:
    image: mohammaddocker/tm-task-api
    environment:
      - MONGO_URL=mongodb://root:task@mongo
      - insecure=false
      - TASK_CERT=/certs/task.pem
      - TASK_KEY=/certs/task-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - PORT=4000
      - AUTH_API_URL=auth-api:4000
      - JAEGER_URL=http://tracing:4318/v1/traces
    # ports:
    #   - 4001:4000
    volumes:
      - ../local/certs:/certs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

  auth-api:
    image: node:18
    working_dir: /app
    environment:
      - MYSQL_URL=mysql://root:passwd@mariadb:3306/auth
      - insecure=false
      - AUTH_CERT=/certs/auth.pem
      - AUTH_KEY=/certs/auth-key.pem
      - PORT=4000
      - USER_API_URL=user-api:4000
      - JWT_SECRET=super-secret
      - USER_CERT=/certs/user.pem
      - USER_KEY=/certs/user-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:4318/v1/traces
    ports:
      - "4002:4000"
    volumes:
      - ../auth-api:/app
      - ../local/certs:/certs
      - /app/node_modules
      - /app/.pnpm-store
    command: bash -c "npm i && npm run start:dev"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

  front:
    image: node:18
    working_dir: /app
    environment:
      - secure=true
      - FRONT_CERT=/certs/front.pem
      - FRONT_KEY=/certs/front-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - PORT=3000
      - USER_API_URL=user-api:4000
      - AUTH_API_URL=auth-api:4000
      - TASK_API_URL=task-api:4000
      - JAEGER_URL=http://tracing:4318/v1/traces
    ports:
      - "3000:5173"
    command: bash -c "npm i && npm run dev"
    volumes:
      - ../front:/app/
      - ../local/certs:/certs
      - /app/node_modules

  media-api:
    image: node:18
    working_dir: /app
    volumes:
      - ../media-api:/app/
      - ../local/certs:/certs
      - /app/node_modules
      - /app/.pnpm-store
    environment:
      - MYSQL_URL=mysql://root:passwd@mariadb:3306/media
      - insecure=false
      - PORT=4000
      - AUTH_API_URL=auth-api:4000
      - MEDIA_CERT=/certs/media.pem
      - MEDIA_KEY=/certs/media-key.pem
      - ROOT_CA=/certs/rootCA.pem
      - JAEGER_URL=http://tracing:14268/api/traces
    ports:
      - "4003:4000"
    command: bash -c "npm i && npm run start:dev"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 5s
      timeout: 10s
      retries: 5

networks:
  default:
    external: true
    name: grpc-task-manager_default
