name: Test E2E of task api

on:
  push:
    branches:
      - ci

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: task
        options: >-
          --health-cmd mongo --eval 'db.runCommand({ ping: 1 })'
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: task-api

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - run: |
          pnpm install
          pnpm run build
          pnpm run start:prod &
        env:
          MONGO_URL: mongodb://root:task@localhost
          insecure: true
          JAEGER_URL: "http://localhost:4318/v1/traces"
          HEALTH_PORT: 3003
          AUTH_API_URL: "localhost:4002"
          PORT: 5004

      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - run: |
          go mod download
          go test
        working-directory: test
