on:
  push:
    branches:
      - ci

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports: 
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: task

    defaults:
      run:
        working-directory: task-api
    
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - run: |
          pnpm i
          pnpm run build
          & pnpm run start:prod
        env:
          MONGO_URL: mongodb://root:task@localhost
          insecure: true
          JAEGER_URL: "http://localhost:4318/v1/traces"
          HEALTH_PORT: 3003
          AUTH_API_URL: "localhost:4002"
          PORT: 5004

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1'
      
      - run: |
          cd test
          go mod download
          go test